# Shell variables
# Generated by 'wal'
wallpaper='/home/sam/.wallpapers/day3.jpg'

# Special
background='#0F3C46'
foreground='#c6dedc'
cursor='#c6dedc'

# Colors
color0='#0F3C46'
color1='#2193AE'
color2='#5F9DA6'
color3='#28A6C8'
color4='#5FB8CC'
color5='#77C4CD'
color6='#C4CEAD'
color7='#c6dedc'
color8='#8a9b9a'
color9='#2193AE'
color10='#5F9DA6'
color11='#28A6C8'
color12='#5FB8CC'
color13='#77C4CD'
color14='#C4CEAD'
color15='#c6dedc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
