--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sam/.wallpapers/day3.jpg"

-- Special
background="#0F3C46"
foreground="#c6dedc"
cursor="#c6dedc"

-- Colors
color0="#0F3C46"
color1="#2193AE"
color2="#5F9DA6"
color3="#28A6C8"
color4="#5FB8CC"
color5="#77C4CD"
color6="#C4CEAD"
color7="#c6dedc"
color8="#8a9b9a"
color9="#2193AE"
color10="#5F9DA6"
color11="#28A6C8"
color12="#5FB8CC"
color13="#77C4CD"
color14="#C4CEAD"
color15="#c6dedc"
